# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
#    format: 'json'
    sort: 'published_at:desc'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Published At', name: date, widget: date, format: 'Do MMM YYYY' }
      - { label: Content, name: body, widget: markdown }
